name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: pnpm
      - name: Run Lint
        run: pnpm run lint